name: gym_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  dio: ^4.0.4
  flutter_barcode_scanner: ^2.0.0
  flutter_web_browser: ^0.17.0
  khalti_flutter: ^2.0.2
  uuid: ^3.0.6
  path_provider: ^2.0.3
  permission_handler: ^8.2.5
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  flutter_secure_storage: ^5.0.2


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: app_icon/icon.png
  ios: true

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 600
